name: element-desktop
on:
  push:
    paths:
    - 'net-im/element-desktop/**'
  pull_request:
    paths:
    - 'net-im/element-desktop/**'

jobs:
  first:
    if: github.repository == 'PF4Public/gentoo-overlay'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Prepare cache dir
        id: prepare
        run: |
          echo "::set-output name=workspace::${GITHUB_WORKSPACE}"
          mkdir -p "${GITHUB_WORKSPACE}/distfiles"

      - name: Find modifications
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        id: files
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate the hash of changed files
        uses: pplanel/hash-calculator-action@v1.3.1
        id: hash
        with:
          input: ${{ steps.files.outputs.modified }} ${{ steps.files.outputs.added }}
          method: MD5

      - name: Cache distfiles
        id: cache-distfiles
        uses: actions/cache@v2
        with:
          path: "${{ steps.prepare.outputs.workspace }}/distfiles"
          key: ${{ github.workflow }}-${{ steps.hash.outputs.digest }}
          restore-keys: ${{ github.workflow }}

      - name: Install ${{ github.workflow }} with default USE-flags
        uses: pf4public/gentoo-docker-action@master
        with:
            added: ${{ steps.files.outputs.added }}
            modified: ${{ steps.files.outputs.modified }}
            tool: ebuild
            action: install
            params: ' '

  ebuild:
    needs: first
    if: github.repository == 'PF4Public/gentoo-overlay'
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        use:
          - 'build-online'
          - 'build-online native-modules'
        include:
          - use: 'electron-20'
            experimental: true

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Prepare cache dir
        id: prepare
        run: |
          echo "::set-output name=workspace::${GITHUB_WORKSPACE}"
          mkdir -p "${GITHUB_WORKSPACE}/distfiles"

      - name: Find modifications
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        id: files
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate the hash of changed files
        uses: pplanel/hash-calculator-action@v1.3.1
        id: hash
        with:
          input: ${{ steps.files.outputs.modified }} ${{ steps.files.outputs.added }}
          method: MD5

      - name: Cache distfiles
        if: ${{ ! contains( matrix.use, 'build-online') || contains( matrix.use, '-build-online')}}
        id: cache-distfiles
        uses: actions/cache@v2
        with:
          path: "${{ steps.prepare.outputs.workspace }}/distfiles"
          key: ${{ github.workflow }}-${{ steps.hash.outputs.digest }}
          restore-keys: ${{ github.workflow }}

      - name: Install ${{ github.workflow }} with "${{ matrix.use }}"
        uses: pf4public/gentoo-docker-action@master
        with:
            added: ${{ steps.files.outputs.added }}
            modified: ${{ steps.files.outputs.modified }}
            tool: ebuild
            action: install
            params: ${{ matrix.use }}
