name: gb-chroot
on:
  push:
    paths:
    - 'app-admin/gb-chroot/**'
  pull_request:
    paths:
    - 'app-admin/gb-chroot/**'

jobs:
  ebuild:
    if: github.repository == 'PF4Public/gentoo-overlay'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        use:
          - doc
          - ''
          - host

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Prepare cache dir
        id: prepare
        run: |
          echo "workspace=${GITHUB_WORKSPACE}" >> $GITHUB_OUTPUT
          mkdir -p "${GITHUB_WORKSPACE}/distfiles"

      - name: Calculate the hash of changed files
        id: hash
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          EVENT_SHA: ${{ github.event.before }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMPARE_BASE=${{ env.BASE_SHA }}
          COMPARE_HEAD=${{ env.HEAD_SHA }}
          MODIFIED_FILES=$(gh api repos/{owner}/{repo}/compare/${COMPARE_BASE:-${{ env.EVENT_SHA }}}...${COMPARE_HEAD:-HEAD} \
            --jq '.files | .[] | select(.status|IN("added", "modified", "renamed", "copied", "changed")) | .filename')
          echo "digest=$( echo "${MODIFIED_FILES}" | md5sum | cut -f 1 -d ' ' )" >> $GITHUB_OUTPUT
          echo "modified=$( echo "${MODIFIED_FILES}" | tr '\n' ' ' )" >> $GITHUB_OUTPUT

      - name: Cache distfiles
        id: cache-distfiles
        uses: actions/cache@v3
        with:
          path: "${{ steps.prepare.outputs.workspace }}/distfiles"
          key: ${{ github.workflow }}-${{ steps.hash.outputs.digest }}
          restore-keys: ${{ github.workflow }}

      - name: Install ${{ github.workflow }} with "${{ matrix.use }}"
        uses: pf4public/gentoo-docker-action@master
        with:
            modified: ${{ steps.hash.outputs.modified }}
            tool: ebuild
            action: install
            params: ${{ matrix.use }}
