name: pkgcheck
on:
  push:
    paths:
    - '**.ebuild'
    - '**.xml'
    - '**Manifest'
    - '!sys-kernel/linux-image/**'
  pull_request:
    paths:
    - '**.ebuild'
    - '**.xml'
    - '**Manifest'
    - '!sys-kernel/linux-image/**'

jobs:
  repoman:
    if: github.repository == 'PF4Public/gentoo-overlay'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: lots0logs/gh-action-get-changed-files@2.1.4
        id: files
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run repoman
        uses: pf4public/gentoo-docker-action@master
        with:
            added: ${{ steps.files.outputs.added }}
            modified: ${{ steps.files.outputs.modified }}
            tool: pkgcheck
            action: scan
            params: -v