name: pkgcheck
on:
  push:
    paths:
    - '**.ebuild'
    - '**.xml'
    - '**Manifest'
    - '!sys-kernel/linux-image/**'
  pull_request:
    paths:
    - '**.ebuild'
    - '**.xml'
    - '**Manifest'
    - '!sys-kernel/linux-image/**'

jobs:
  pkgcheck:
    if: github.repository == 'PF4Public/gentoo-overlay'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Calculate the hash of changed files
        id: hash
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          EVENT_SHA: ${{ github.event.before }}
          EVENT_HEAD: ${{ github.event.head }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMPARE_BASE=${{ env.BASE_SHA }}
          COMPARE_HEAD=${{ env.HEAD_SHA }}
          COMPARE_HEAD=${COMPARE_HEAD:-${{ env.EVENT_HEAD }}}
          MODIFIED_FILES=$(gh api repos/{owner}/{repo}/compare/${COMPARE_BASE:-${{ env.EVENT_SHA }}}...${COMPARE_HEAD:-HEAD} \
            --jq '.files | .[] | select(.status|IN("added", "modified", "renamed", "copied", "changed")) | .filename')
          echo "digest=$( echo "${MODIFIED_FILES}" | md5sum | cut -f 1 -d ' ' )" >> $GITHUB_OUTPUT
          echo "modified=$( echo "${MODIFIED_FILES}" | tr '\n' ' ' )" >> $GITHUB_OUTPUT

      - name: Run pkgcheck
        uses: pf4public/gentoo-docker-action@master
        with:
            modified: ${{ steps.hash.outputs.modified }}
            tool: pkgcheck
            action: scan
            params: -v --exit error