name: sb-hosts
on:
  push:
    paths:
    - 'net-misc/sb-hosts/**'
  pull_request:
    paths:
    - 'net-misc/sb-hosts/**'

jobs:
  ebuild:
    if: github.repository == 'PF4Public/gentoo-overlay'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        use:
          - fakenews gambling porn social
          - fakenews gambling social
          - fakenews social
          - gambling
          - ''

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Calculate the hash of changed files
        id: hash
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          EVENT_SHA: ${{ github.event.before }}
          EVENT_HEAD: ${{ github.event.head }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMPARE_BASE=${{ env.BASE_SHA }}
          COMPARE_HEAD=${{ env.HEAD_SHA }}
          COMPARE_HEAD=${COMPARE_HEAD:-${{ env.EVENT_HEAD }}}
          MODIFIED_FILES=$(gh api repos/{owner}/{repo}/compare/${COMPARE_BASE:-${{ env.EVENT_SHA }}}...${COMPARE_HEAD:-HEAD} \
            --jq '.files | .[] | select(.status|IN("added", "modified", "renamed", "copied", "changed")) | .filename')
          echo "digest=$( echo "${MODIFIED_FILES}" | md5sum | cut -f 1 -d ' ' )" >> $GITHUB_OUTPUT
          echo "modified=$( echo "${MODIFIED_FILES}" | tr '\n' ' ' )" >> $GITHUB_OUTPUT

      - name: Install ${{ github.workflow }} with "${{ matrix.use }}"
        uses: pf4public/gentoo-docker-action@master
        with:
            modified: ${{ steps.hash.outputs.modified }}
            tool: ebuild
            action: install
            params: ${{ matrix.use }}
