name: ungoogled-chromium
on:
  push:
    paths:
    - 'www-client/ungoogled-chromium/**'
  pull_request:
    paths:
    - 'www-client/ungoogled-chromium/**'

jobs:
  first:
    if: github.repository == 'PF4Public/gentoo-overlay'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Prepare cache dir
        id: prepare
        run: |
          echo "::set-output name=workspace::${GITHUB_WORKSPACE}"
          mkdir -p "${GITHUB_WORKSPACE}/distfiles"

      - name: Find modifications
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        id: files
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate the hash of changed files
        uses: pplanel/hash-calculator-action@v1.3.1
        id: hash
        with:
          input: ${{ steps.files.outputs.modified }} ${{ steps.files.outputs.added }}
          method: MD5

      - name: Cache distfiles
        id: cache-distfiles
        uses: actions/cache@v3
        with:
          path: "${{ steps.prepare.outputs.workspace }}/distfiles"
          key: ${{ github.workflow }}-${{ steps.hash.outputs.digest }}
          restore-keys: ${{ github.workflow }}

      - name: Configure ${{ github.workflow }} with default USE-flags
        uses: pf4public/gentoo-docker-action@master
        with:
            added: ${{ steps.files.outputs.added }}
            modified: ${{ steps.files.outputs.modified }}
            tool: ebuild
            action: configure
            params: ' '

  ebuild:
    needs: first
    if: github.repository == 'PF4Public/gentoo-overlay'
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        use:
          - -clang
          - custom-cflags
          - vaapi -system-libvpx
          - vdpau
          - -official
          - wayland
        include:
          - use: headless -X -wayland
            experimental: true
          - use: vaapi system-libvpx
            experimental: true
          - use: system-libvpx
            experimental: true
          - use: pgo
            experimental: true
          - use: thinlto optimize-thinlto
            experimental: true
          - use: cfi thinlto
            experimental: true

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Prepare cache dir
        id: prepare
        run: |
          echo "::set-output name=workspace::${GITHUB_WORKSPACE}"
          mkdir -p "${GITHUB_WORKSPACE}/distfiles"

      - name: Find modifications
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        id: files
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate the hash of changed files
        uses: pplanel/hash-calculator-action@v1.3.1
        id: hash
        with:
          input: ${{ steps.files.outputs.modified }} ${{ steps.files.outputs.added }}
          method: MD5

      - name: Cache distfiles
        id: cache-distfiles
        uses: actions/cache@v3
        with:
          path: "${{ steps.prepare.outputs.workspace }}/distfiles"
          key: ${{ github.workflow }}-${{ steps.hash.outputs.digest }}
          restore-keys: ${{ github.workflow }}

      - name: Configure ${{ github.workflow }} with "${{ matrix.use }}"
        uses: pf4public/gentoo-docker-action@master
        with:
            added: ${{ steps.files.outputs.added }}
            modified: ${{ steps.files.outputs.modified }}
            tool: ebuild
            action: configure
            params: ${{ matrix.use }}
