name: vscode
on:
  push:
    paths:
    - 'app-editors/vscode/**'
  pull_request:
    paths:
    - 'app-editors/vscode/**'

jobs:
  default:
    if: github.repository == 'PF4Public/gentoo-overlay'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Prepare cache dir
        id: prepare
        run: |
          echo "workspace=${GITHUB_WORKSPACE}" >> $GITHUB_OUTPUT
          mkdir -p "${GITHUB_WORKSPACE}/distfiles"

      - name: Calculate the hash of changed files
        id: hash
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}${{ github.event.before }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          MODIFIED_FILES=$(gh api repos/{owner}/{repo}/compare/${{ env.BASE_SHA }}...HEAD \
            --jq '.files | .[] | select(.status|IN("added", "modified", "renamed", "copied", "changed")) | .filename')
          echo "digest=$( echo "${MODIFIED_FILES}" | md5sum | cut -f 1 -d ' ' )" >> $GITHUB_OUTPUT
          echo "modified=$( echo "${MODIFIED_FILES}" | tr '\n' ' ' )" >> $GITHUB_OUTPUT

      - name: Cache distfiles
        id: cache-distfiles
        uses: actions/cache@v3
        with:
          path: "${{ steps.prepare.outputs.workspace }}/distfiles"
          key: ${{ github.workflow }}-${{ steps.hash.outputs.digest }}
          restore-keys: ${{ github.workflow }}

      - name: Install ${{ github.workflow }} with default USE-flags
        uses: pf4public/gentoo-docker-action@master
        with:
            modified: ${{ steps.hash.outputs.modified }}
            tool: ebuild
            action: install
            params: ' '

  ebuild:
    needs: default
    if: github.repository == 'PF4Public/gentoo-overlay'
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        use:
          - 'badge-providers insiders liveshare'
          - 'openvsx'
          - 'substitute-urls'
          - 'build-online'
        include:
          - use: 'electron-20'
            experimental: true
          - use: 'electron-21'
            experimental: true
          - use: 'electron-22'
            experimental: true
          - use: 'electron-23'
            experimental: true

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Prepare cache dir
        id: prepare
        run: |
          echo "workspace=${GITHUB_WORKSPACE}" >> $GITHUB_OUTPUT
          mkdir -p "${GITHUB_WORKSPACE}/distfiles"

      - name: Calculate the hash of changed files
        id: hash
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}${{ github.event.before }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          MODIFIED_FILES=$(gh api repos/{owner}/{repo}/compare/${{ env.BASE_SHA }}...HEAD \
            --jq '.files | .[] | select(.status|IN("added", "modified", "renamed", "copied", "changed")) | .filename')
          echo "digest=$( echo "${MODIFIED_FILES}" | md5sum | cut -f 1 -d ' ' )" >> $GITHUB_OUTPUT
          echo "modified=$( echo "${MODIFIED_FILES}" | tr '\n' ' ' )" >> $GITHUB_OUTPUT

      - name: Cache distfiles
        if: ${{ ! contains( matrix.use, 'build-online') || contains( matrix.use, '-build-online')}}
        id: cache-distfiles
        uses: actions/cache@v3
        with:
          path: "${{ steps.prepare.outputs.workspace }}/distfiles"
          key: ${{ github.workflow }}-${{ steps.hash.outputs.digest }}
          restore-keys: ${{ github.workflow }}

      - name: Install ${{ github.workflow }} with "${{ matrix.use }}"
        uses: pf4public/gentoo-docker-action@master
        with:
            modified: ${{ steps.hash.outputs.modified }}
            tool: ebuild
            action: install
            params: ${{ matrix.use }}
